"""
Generate docs/cli.md from the `ml` (``python -m src.cli``) command definitions.

Reads the Typer app's click commands, so every option, default and help text
on the page is exactly what ``python -m src.cli <command> --help`` prints.

Usage:
    python scripts/gen_cli_docs.py            # write docs/cli.md
    python scripts/gen_cli_docs.py --check    # exit 1 if the page is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import typer

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src.cli.unified_cli import app  # noqa: E402

OUT = REPO_ROOT / "docs" / "cli.md"
PROG = "python -m src.cli"

INTRO = """\
# CLI reference

<!-- Generated by scripts/gen_cli_docs.py from the Typer app. Do not edit by hand:
run `make docs-gen`. -->

One pipeline sits behind every command: raw OHLCV bars -> `FeatureEngineer` ->
triple-barrier labels (with label spans) -> models. There are no intermediate
stage directories; every command that reads data takes the raw bars (`-d`,
parquet or csv) and applies the same cleaning, resampling and feature code as
`MLFactory` and the deployed bundles.

`ml` below is shorthand for `python -m src.cli`. Results go to
`<output_dir>/<run_id>/`; the evaluation commands (`cv`, `walk-forward`,
`cpcv-pbo`) evaluate the chronological **train split only** (validation and
test stay untouched), scale per fold, and purge on every label's actual end
bar with the derived purge/embargo (`--purge-bars` / `--embargo-bars`
override).

```bash
# Train xgboost + lstm + patchtst on 5-minute bars, stack with soft voting, backtest
ml run -d data/raw/MES_1m.parquet --bar-timeframe 5min \\
    -m xgboost,lstm,patchtst --build-ensemble --meta-learner voting_meta -h 5 --backtest

ml status experiments/<run_id>          # checkpoint progress
ml run --resume experiments/<run_id>    # continue after a crash
ml cpcv-pbo -d data/raw/MES_1m.parquet -m xgboost,lightgbm,random_forest
```
"""


def _is_option(param: Any) -> bool:
    return param.param_type_name == "option"


def _type_label(param: Any) -> str:
    if _is_option(param) and param.is_flag:
        return "flag"
    name = getattr(param.type, "name", str(param.type))
    return {
        "text": "TEXT",
        "str": "TEXT",
        "string": "TEXT",
        "integer": "INT",
        "float": "FLOAT",
        "path": "PATH",
    }.get(name, name.upper())


def _default(param: Any) -> str:
    if param.required:
        return "required"
    default = param.default
    if callable(default) or default is None or default == ():
        return ""
    if _is_option(param) and param.is_flag:
        if param.secondary_opts:
            names = param.opts if default else param.secondary_opts
            return f"`{names[0]}`"
        return "off" if not default else "on"
    return f"`{default}`"


def _escape(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _command_section(name: str, cmd: Any) -> list[str]:
    ctx = typer.Context(cmd, info_name=f"{PROG} {name}")
    usage = cmd.get_usage(ctx).removeprefix("Usage: ")
    help_text = inspect_help(cmd)
    lines = [f"## `ml {name}`", "", help_text, "", "```text", usage, "```", ""]
    args = [p for p in cmd.params if p.param_type_name == "argument"]
    opts = [p for p in cmd.params if _is_option(p) and p.name != "help"]
    if args:
        lines += ["| Argument | Type | Description |", "|---|---|---|"]
        for p in args:
            desc = _escape(getattr(p, "help", None) or "")
            req = "required" if p.required else "optional"
            lines.append(f"| `{(p.name or '').upper()}` | {_type_label(p)}, {req} | {desc} |")
        lines.append("")
    if opts:
        lines += ["| Option | Type | Default | Description |", "|---|---|---|---|"]
        for p in opts:
            flags = ", ".join(f"`{o}`" for o in [*p.opts, *p.secondary_opts])
            lines.append(
                f"| {flags} | {_type_label(p)} | {_default(p)} | {_escape(p.help or '')} |"
            )
        lines.append("")
    return lines


def inspect_help(cmd: Any) -> str:
    """Command help text (first paragraph kept as the lead, the rest verbatim)."""
    text = (cmd.help or cmd.short_help or "").strip()
    return "\n".join(line.strip() for line in text.splitlines())


def render() -> str:
    group: Any = typer.main.get_command(app)  # a click Group (typer vendors click)
    ctx = typer.Context(group, info_name=PROG)
    lines = [INTRO, "## Commands", "", "| Command | Purpose |", "|---|---|"]
    names = group.list_commands(ctx)
    for name in names:
        cmd = group.get_command(ctx, name)
        assert cmd is not None
        first = inspect_help(cmd).split("\n")[0]
        lines.append(f"| [`ml {name}`](#ml-{name}) | {_escape(first)} |")
    lines.append("")
    for name in names:
        cmd = group.get_command(ctx, name)
        assert cmd is not None
        lines += _command_section(name, cmd)
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if the page is stale")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            sys.exit(f"{OUT.relative_to(REPO_ROOT)} is stale: run `make docs-gen`")
        print(f"{OUT.relative_to(REPO_ROOT)} is up to date")
        return
    OUT.write_text(text)
    print(f"Wrote {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
