#!/usr/bin/env python3
"""
Generate model inventory from ModelRegistry.

This script queries the ModelRegistry to produce an up-to-date inventory
of all registered models, formatted as markdown tables for documentation.

Usage:
    python scripts/generate_model_inventory.py
    python scripts/generate_model_inventory.py --format json
    python scripts/generate_model_inventory.py --output docs/reference/MODEL_INVENTORY.md

The output can be used to update documentation in:
- docs/README.md (Current Implementation Summary section)
- docs/planning/PROJECT_CHARTER.md (Model Inventory section)
- docs/reference/MODELS.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Add project root to path for imports
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


def get_model_inventory() -> dict:
    """
    Query ModelRegistry and return structured inventory data.

    Returns:
        dict with keys:
        - total_count: Total number of models
        - families: Dict mapping family names to list of model info dicts
        - summary: Summary statistics
    """
    # Import here to avoid import errors if dependencies missing
    from src.models import ModelRegistry

    # Trigger model registration by importing all model modules
    try:
        from src.models import boosting  # noqa: F401
        from src.models import classical  # noqa: F401
        from src.models import ensemble  # noqa: F401
        from src.models import neural  # noqa: F401
    except ImportError as e:
        print(f"Warning: Could not import all model modules: {e}", file=sys.stderr)

    # Get all models by family
    families_raw = ModelRegistry.list_models()
    total_count = ModelRegistry.count()

    # Build structured inventory
    families = {}
    for family_name, model_names in families_raw.items():
        models = []
        for model_name in model_names:
            try:
                metadata = ModelRegistry.get_metadata(model_name)
                # Check if model is actually available (dependencies installed)
                is_available = ModelRegistry.is_available(model_name)
                models.append({
                    "name": model_name,
                    "description": metadata.get("description", ""),
                    "class": metadata.get("class", ""),
                    "aliases": metadata.get("aliases", []),
                    "available": is_available,
                })
            except Exception as e:
                print(f"Warning: Could not get metadata for {model_name}: {e}", file=sys.stderr)
                models.append({
                    "name": model_name,
                    "description": "",
                    "class": "",
                    "aliases": [],
                    "available": False,
                })
        families[family_name] = models

    # Count available models
    available_count = sum(
        1 for family_models in families.values()
        for model in family_models
        if model["available"]
    )

    return {
        "total_count": total_count,
        "available_count": available_count,
        "families": families,
        "summary": {
            "families": list(families.keys()),
            "family_counts": {k: len(v) for k, v in families.items()},
        },
    }


def format_markdown(inventory: dict) -> str:
    """Format inventory as markdown."""
    lines = []

    lines.append("# Model Inventory")
    lines.append("")
    lines.append(f"**Total Models:** {inventory['total_count']}")
    lines.append(f"**Available Models:** {inventory['available_count']}")
    lines.append(f"**Families:** {len(inventory['families'])}")
    lines.append("")
    lines.append("> This file is auto-generated by `python scripts/generate_model_inventory.py`")
    lines.append("")

    # Summary table
    lines.append("## Summary by Family")
    lines.append("")
    lines.append("| Family | Count | Models |")
    lines.append("|--------|-------|--------|")
    for family_name, models in sorted(inventory["families"].items()):
        model_names = ", ".join(m["name"] for m in models)
        lines.append(f"| **{family_name.capitalize()}** | {len(models)} | {model_names} |")
    lines.append("")

    # Detailed tables by family
    lines.append("## Detailed Model List")
    lines.append("")

    for family_name, models in sorted(inventory["families"].items()):
        lines.append(f"### {family_name.capitalize()} ({len(models)} models)")
        lines.append("")
        lines.append("| Model | Class | Available | Description |")
        lines.append("|-------|-------|-----------|-------------|")
        for model in models:
            available_mark = "Yes" if model["available"] else "No"
            desc = model["description"][:60] + "..." if len(model["description"]) > 60 else model["description"]
            lines.append(f"| `{model['name']}` | {model['class']} | {available_mark} | {desc} |")
        lines.append("")

    return "\n".join(lines)


def format_json(inventory: dict) -> str:
    """Format inventory as JSON."""
    return json.dumps(inventory, indent=2)


def format_summary(inventory: dict) -> str:
    """Format a brief summary for embedding in other docs."""
    lines = []

    lines.append(f"**Models by Family ({len(inventory['families'])} Families, {inventory['total_count']} Models):**")
    lines.append("")

    for family_name, models in sorted(inventory["families"].items()):
        model_names = ", ".join(m["name"].replace("_", " ").title() for m in models)
        lines.append(f"- **{family_name.capitalize()} ({len(models)}):** {model_names}")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate model inventory from ModelRegistry",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--format",
        choices=["markdown", "json", "summary"],
        default="markdown",
        help="Output format (default: markdown)",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        help="Output file path (default: stdout)",
    )

    args = parser.parse_args()

    # Get inventory
    inventory = get_model_inventory()

    # Format output
    if args.format == "json":
        output = format_json(inventory)
    elif args.format == "summary":
        output = format_summary(inventory)
    else:
        output = format_markdown(inventory)

    # Write output
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output)
        print(f"Wrote inventory to {args.output}")
    else:
        print(output)

    # Print summary to stderr
    print(
        f"\nInventory: {inventory['total_count']} models in "
        f"{len(inventory['families'])} families "
        f"({inventory['available_count']} available)",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
