"""
Compatibility configuration facade for tests and standalone utilities.
"""
from __future__ import annotations

from src.common.horizon_config import (
    HORIZONS,
    SUPPORTED_HORIZONS,
    ACTIVE_HORIZONS,
    LOOKBACK_HORIZONS,
    HORIZON_TIMEFRAME_MINUTES,
    validate_horizons,
    get_scaled_horizons,
    auto_scale_purge_embargo,
    get_default_barrier_params_for_horizon,
)
from src.phase1.config import (
    # barrier config
    BARRIER_PARAMS,
    BARRIER_PARAMS_DEFAULT,
    PERCENTAGE_BARRIER_PARAMS,
    TRANSACTION_COSTS,
    SLIPPAGE_TICKS,
    TICK_VALUES,
    get_barrier_params,
    get_slippage_ticks,
    get_total_trade_cost,
    get_max_bars_across_all_params,
    validate_barrier_params,
    # labeling + regime
    LabelingStrategyType,
    DEFAULT_LABELING_STRATEGY,
    LABELING_STRATEGY_CONFIGS,
    LABEL_BALANCE_CONSTRAINTS,
    MULTI_LABEL_CONFIG,
    get_labeling_strategy_config,
    get_multi_label_config,
    validate_labeling_config,
    REGIME_CONFIG,
    REGIME_BARRIER_ADJUSTMENTS,
    get_regime_adjusted_barriers,
    # timeframe config
    SUPPORTED_TIMEFRAMES,
    TIMEFRAME_TO_FREQ,
    validate_timeframe as _validate_timeframe,
    parse_timeframe_to_minutes,
    # feature config
    CORRELATION_THRESHOLD,
    VARIANCE_THRESHOLD,
    CROSS_ASSET_FEATURES,
    MTF_CONFIG,
    STATIONARITY_TESTS,
    DRIFT_CONFIG,
    get_mtf_config,
    validate_mtf_config,
    get_cross_asset_config,
    validate_feature_thresholds,
    get_stationarity_config,
    validate_stationarity_config,
    get_drift_config,
    validate_drift_config,
    get_cross_asset_feature_names,
    is_cross_asset_feature,
    # label templates
    REQUIRED_LABEL_TEMPLATES,
    OPTIONAL_LABEL_TEMPLATES,
    ALL_LABEL_TEMPLATES,
    LABEL_COLUMN_METADATA,
    get_required_label_columns,
    get_optional_label_columns,
    get_all_label_columns,
    is_label_column,
    get_label_metadata,
    # runtime defaults
    PROJECT_ROOT,
    DATA_DIR,
    RAW_DATA_DIR,
    RESULTS_DIR,
    RUNS_DIR,
    CONFIG_DIR,
    SYMBOLS,
    TARGET_TIMEFRAME,
    TRAIN_RATIO,
    VAL_RATIO,
    TEST_RATIO,
    RANDOM_SEED,
    PURGE_BARS,
    EMBARGO_BARS,
    set_global_seeds,
    validate_config,
    get_timeframe_metadata,
)


def validate_timeframe(timeframe: str) -> bool:
    """Return True for valid timeframes, raise ValueError otherwise."""
    _validate_timeframe(timeframe)
    return True


__all__ = [
    # horizon_config
    "HORIZONS",
    "SUPPORTED_HORIZONS",
    "ACTIVE_HORIZONS",
    "LOOKBACK_HORIZONS",
    "HORIZON_TIMEFRAME_MINUTES",
    "validate_horizons",
    "get_scaled_horizons",
    "auto_scale_purge_embargo",
    "get_default_barrier_params_for_horizon",
    # barrier config
    "BARRIER_PARAMS",
    "BARRIER_PARAMS_DEFAULT",
    "PERCENTAGE_BARRIER_PARAMS",
    "TRANSACTION_COSTS",
    "SLIPPAGE_TICKS",
    "TICK_VALUES",
    "get_barrier_params",
    "get_slippage_ticks",
    "get_total_trade_cost",
    "get_max_bars_across_all_params",
    "validate_barrier_params",
    # labeling + regime
    "LabelingStrategyType",
    "DEFAULT_LABELING_STRATEGY",
    "LABELING_STRATEGY_CONFIGS",
    "LABEL_BALANCE_CONSTRAINTS",
    "MULTI_LABEL_CONFIG",
    "get_labeling_strategy_config",
    "get_multi_label_config",
    "validate_labeling_config",
    "REGIME_CONFIG",
    "REGIME_BARRIER_ADJUSTMENTS",
    "get_regime_adjusted_barriers",
    # timeframe config
    "SUPPORTED_TIMEFRAMES",
    "TIMEFRAME_TO_FREQ",
    "validate_timeframe",
    "parse_timeframe_to_minutes",
    # feature config
    "CORRELATION_THRESHOLD",
    "VARIANCE_THRESHOLD",
    "CROSS_ASSET_FEATURES",
    "MTF_CONFIG",
    "STATIONARITY_TESTS",
    "DRIFT_CONFIG",
    "get_mtf_config",
    "validate_mtf_config",
    "get_cross_asset_config",
    "validate_feature_thresholds",
    "get_stationarity_config",
    "validate_stationarity_config",
    "get_drift_config",
    "validate_drift_config",
    "get_cross_asset_feature_names",
    "is_cross_asset_feature",
    # label templates
    "REQUIRED_LABEL_TEMPLATES",
    "OPTIONAL_LABEL_TEMPLATES",
    "ALL_LABEL_TEMPLATES",
    "LABEL_COLUMN_METADATA",
    "get_required_label_columns",
    "get_optional_label_columns",
    "get_all_label_columns",
    "is_label_column",
    "get_label_metadata",
    # runtime defaults
    "PROJECT_ROOT",
    "DATA_DIR",
    "RAW_DATA_DIR",
    "RESULTS_DIR",
    "RUNS_DIR",
    "CONFIG_DIR",
    "SYMBOLS",
    "TARGET_TIMEFRAME",
    "TRAIN_RATIO",
    "VAL_RATIO",
    "TEST_RATIO",
    "RANDOM_SEED",
    "PURGE_BARS",
    "EMBARGO_BARS",
    "set_global_seeds",
    "validate_config",
    "get_timeframe_metadata",
]
